# nixpacks.toml

version = 1  # Nixpacks file version

# Define builders for backend and frontend
[builders.backend]
    steps = [
        { name = "install backend dependencies", command = "npm install", path = "/server" },  # Path to backend directory
        { name = "start backend server", command = "node server.js", path = "/server" }      # Path to backend directory
    ]

[builders.frontend]
    steps = [
        { name = "install frontend dependencies", command = "npm install", path = "/client" },  # Path to frontend directory
        { name = "build frontend", command = "npm run build", path = "./client" },
        {name = "start frontend", command = "npm start" , path = "/client" } # 
    ]

# Define services using the builders
[services.backend]
    build = "backend"  # Use the backend builder
    port = 8000        # Expose the backend on port 8000

[services.frontend]
    build = "frontend"  # Use the frontend builder
    port = 3000
    env = { REACT_APP_API_URL = "https://server-productmanager.up.railway.app" }  # Replace with your backend URL
    # You may specify ports if necessary, otherwise, frontend typically runs on a different port and is accessed through the backend
